dashboard/urls.py
from django.conf.urls import url
from django.urls import path, register_converter
from django.urls.converters import AcademyConverter, KlassConverter, PersonalConverter
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (

    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

)

from dashboard import views

register_converter(AcademyConverter, 'academy_id')
register_converter(KlassConverter, 'klass_id')
register_converter(PersonalConverter, 'student_id')

app_name = 'dashboard'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('me/', views.me_view, name='me_view'),
    path('me/signupkey/', views.sign_up_key_view, name='sign_up_key'),
    path('me/edit/', views.profile_edit_view, name='profile_edit'),
    path('me/password/', views.password_edit_view, name='password_edit'),

    path('import/choose/', views.import_choose_view, name='import_choose'),
    path('import/students/<int:aca_id>/', views.import_student_view, name='import_student'),

    path('category/create/', views.category_create_view, name='category_create'),
    path('category/manage/', views.category_manage_view, name='category_manage'),
    path('category/change/<int:cat_id>/', views.category_change_view, name='category_change'),

    path('notification/create/', views.notification_create_view, name='notification_create'),
    path('notification/manage/', views.notification_manage_view, name='notification_manage'),
    path('notification/change/<int:ntf_id>/', views.notification_change_view, name='notification_change'),
    # path('notification/delete/<int:ntf_id>', views.notification_delete_view, name='notification_delete'),

    path('academy/create/', views.academy_create_view, name='academy_create'),
    path('academy/manage/', views.academy_manage_view, name='academy_manage'),
    path('academy/change/<int:aca_id>/', views.academy_change_view, name='academy_change'),
    # path('academy/delete/<int:aca_id>', views.academy_delete_view, name='academy_delete'),
    path('academy/view/<academy_id:aca_id>/', views.academy_view_view, name='academy_view'),

    path('klass/create/', views.klass_create_view, name='klass_create'),
    path('klass/manage/', views.klass_manage_view, name='klass_manage'),
    path('klass/change/<int:kls_id>/', views.klass_change_view, name='klass_change'),
    # path('klass/delete/<int:kls_id>', views.klass_delete_view, name='klass_delete'),
    path('klass/view/<klass_id:kls_id>/', views.klass_view_view, name='klass_view'),

    path('question/create/', views.question_create_view, name='question_create'),
    path('question/manage/', views.question_manage_view, name='question_manage'),
    path('question/change/<uuid:qes_id>/', views.question_change_view, name='question_change'),
    # path('question/delete/<uuid:qes_id>', views.question_delete_view, name='question_delete'),
    path('choice/change/<uuid:cho_id>/', views.choice_change_view, name='choice_change'),
    path('question/list/', views.question_list_view, name='question_list'),

    path('exam/create/', views.exam_create_view, name='exam_create'),
    path('exam/manage/', views.exam_manage_view, name='exam_manage'),
    path('exam/change/<uuid:exa_id>/', views.exam_change_view, name='exam_change'),
    # path('exam/delete/<uuid:exa_id>', views.exam_delete_view, name='exam_delete'),
    path('exam/info/<uuid:exa_id>/', views.exam_info_view, name='exam_info'),
    path('exam/start/<uuid:exa_id>/', views.exam_start_view, name='exam_start'),
    path('exam/end/<uuid:exa_id>/', views.exam_end_view, name='exam_end'),
    path('exam/examing/<uuid:exa_id>/', views.exam_examing_view, name='exam_examing'),
    path('exam/list/', views.exam_list_view, name='exam_list'),
    path('exam/score/', views.exam_score_view, name='exam_score'),
    path('exam/score/klass/<int:kls_id>/', views.supervisor_exam_klass_list_for_score_view,
         name='exam_klass_list_score'),
    path('exam/score/exam/<uuid:exa_id>/', views.supervisor_exam_list_for_score_view, name='exam_list_score'),
    path('exam/score/exam/<uuid:exa_id>/list/', views.supervisor_exam_score_list_view, name='exam_score_list'),
    path('exam/score/exam/<uuid:exa_id>/list/<int:student>/', views.supervisor_exam_score_for_student_list_view,
         name='exam_score_for_student_list'),
    path('exam/score/exam/<uuid:exa_id>/excel/', views.supervisor_exam_score_excel_view, name='exam_score_excel'),

    # path('exam/score/<uuid:exa_id>/', views.exam_score_list_supervisor_view, name='exam_score_list'),

    path('delete/<str:name>/<int:obj_id>/', views.delete_objects_view, name='delete_none_uuid'),
    path('delete/<str:name>/<uuid:obj_uuid>/', views.delete_uuid_objects_view, name='delete_uuid'),
    path('changepass/<str:name>/<int:user_id>/', views.changepass_user_view, name='changepass_user'),

    path('list/supervisor/', views.list_supervisor_view, name='list_supervisor'),
    path('list/teacher/', views.list_teacher_view, name='list_teacher'),
    path('list/student/', views.list_student_view, name='list_student'),
    path('list/all/<str:name>/', views.list_all_view, name='list_all'),

    path('copy/obj/<str:name>/', views.copy_object_view, name='copy_obj'),

    path('wallet/<int:wal_id>/', views.wallet_increase_view, name='wallet_increase'),
    path('wallet/transaction/list/', views.wallet_transaction_list_view, name='wallet_transaction_list'),

    path('admin/ec/score/', views.extra_exam_checker, name='extra_exam_checker'),
    path('admin/ec/rescore/<uuid:exa_id>/', views.extra_score_checker, name='extra_score_checker'),
    path('admin/ec/rescore/stu/<int:stu_id>/', views.extra_score_checker_student, name='extra_score_checker_student'),
]

online_exam_system/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from dashboard import views
from online_exam_system import settings

# from django.conf.urls.static import static


urlpatterns = [
    path('', views.home_page_view, name='home_page'),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    url(r'', include('webmaster_verification.urls')),
]
# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/views.py
import openpyxl
import xlsxwriter
from openpyxl.utils import get_column_letter
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from django.core.files import File
from django.core.files.storage import FileSystemStorage
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from psycopg2 import errorcodes
import random
import io

from django.urls import reverse
from psycopg2.errorcodes import UNIQUE_VIOLATION

from dashboard.forms import *
from dashboard.models import *


def pagination_template(request, source, divide_by=2, page_name='page'):
    page = request.GET.get(page_name, 1)
    paginator = Paginator(source, divide_by)
    try:
        pager = paginator.page(page)
    except PageNotAnInteger:
        pager = paginator.page(1)
    except EmptyPage:
        pager = paginator.page(paginator.num_pages)

    return pager


def pagination_template_long(request, source, divide_by=2, page_name='page'):
    page = request.GET.get(page_name, 1)
    paginator = Paginator(source, divide_by)
    try:
        pager = paginator.page(page)
    except PageNotAnInteger:
        pager = paginator.page(1)
    except EmptyPage:
        pager = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = pager.number - 1  # edited to something easier without index
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 7, so lets calculate where to slice the list
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    # Get our new page range. In the latest versions of Django page_range returns
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]

    return pager, page_range


def pagination_show(request, all_objects, divide_by=6):
    if len(all_objects) == 0:
        return {
            'color': 'danger',
            'text': ' موردی یافت نشد!',
        }
    else:
        return pagination_template(request, source=all_objects, divide_by=divide_by)


def pagination_show_long(request, all_objects, divide_by=6):
    if len(all_objects) == 0:
        return {
            'color': 'danger',
            'text': ' موردی یافت نشد!',
        }
    else:
        return pagination_template_long(request, source=all_objects, divide_by=divide_by)


def signup_view(request):
    notification = Notification.objects.filter(show_on_signup=True).order_by('-date')
    if request.method == 'POST':
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            signup_form.save(commit=False)
            if signup_form.cleaned_data.get('user_type') == 1:
                signup_form.instance.is_student = True
            elif signup_form.cleaned_data.get('user_type') == 2:
                signup_form.instance.is_teacher = True
            elif signup_form.cleaned_data.get('user_type') == 3:
                signup_form.instance.is_supervisor = True
            signup_form.save()
            username = signup_form.cleaned_data.get('username')
            raw_password = signup_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('dashboard:me_view'))
    else:
        signup_form = SignUpForm()
        # signup_form_username = CustomAuthenticationForm
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home_page'))
    context = {
        'signup_form': signup_form,
        'notification': notification,
        # 'signup_form_username': signup_form_username,
    }
    return render(request, 'dashboard/signup.html', context)


def login_view(request):
    notification = Notification.objects.filter(show_on_login=True).order_by('-date')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {
                'username': username,
                'error': 'نام کاربری یا رمز عبور اشتباه است!',
                'notification': notification,
            }
        else:
            login(request, user)
            # return HttpResponseRedirect(reverse('home_page'))
            return HttpResponseRedirect(reverse('dashboard:me_view'))
    elif request.user.is_authenticated:
        # return HttpResponseRedirect(reverse('home_page'))
        return HttpResponseRedirect(reverse('dashboard:me_view'))
    else:
        context = {
            'notification': notification,
        }
    return render(request, 'dashboard/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('dashboard:login'))


# def superuser_dashboard(request):
#     temp_user = request.user
#     temp_profile = Profile.objects.get(user=temp_user)
#     # temp_student = Profile.objects.filter(user__is_student=True)
#     # temp_teacher = Profile.objects.filter(user__is_teacher=True)
#     # temp_supervisor = Profile.objects.filter(user__is_supervisor=True)
#     # temp_notification = Notification.objects.all().order_by('-date')
#     # temp_academy = Academy.objects.all()
#     # temp_klass = Klass.objects.all()
#     # temp_exam = Exam.objects.all()
#     # temp_question = Question.objects.all()
#     # temp_score = StudentScore.objects.all()
#     # temp_category = Category.objects.all()
#     return {
#         'is_superuser': True,
#         'user': temp_user,
#         'profile': temp_profile,
#         # 'student': temp_student,
#         # 'teacher': temp_teacher,
#         # 'supervisor': temp_supervisor,
#         # 'notification': temp_notification,
#         # 'academy': temp_academy,
#         # 'klass': temp_klass,
#         # 'exam': temp_exam,
#         # 'question': temp_question,
#         # 'score': temp_score,
#         # 'category': temp_category,
#     }
#
#
# def supervisor_dashboard(request):
#     temp_user = request.user
#     temp_profile = Profile.objects.get(user=temp_user)
#     temp_supervisor = Profile.objects.get(Q(user=temp_user) & Q(user__is_supervisor=True))
#     temp_academy = temp_profile.academy
#     temp_teacher = Profile.objects.filter(Q(user__profile__academy=temp_academy) & Q(user__is_teacher=True))
#     temp_student = Profile.objects.filter(Q(user__profile__academy=temp_academy) & Q(user__is_student=True))
#     temp_klass = Klass.objects.filter(academy=temp_academy)
#     temp_exam = Exam.objects.filter(exam_klass__academy=temp_academy).order_by('-exam_finish')
#     temp_score = StudentScore.objects.filter(student__user__profile__academy=temp_academy).order_by('-exam')
#     temp_wallet = Wallet.objects.get(user=temp_user)
#     temp_transaction = Transaction.objects.filter(wallet__user=temp_user).order_by('-order_time')
#     temp_question = []
#     for i in temp_teacher:
#         x = Question.objects.filter(creator=i)
#         for j in x:
#             temp_question.append(j)
#     return {
#         'is_supervisor': True,
#         'user': temp_user,
#         'profile': temp_profile,
#         'supervisor': temp_supervisor,
#         'teacher': temp_teacher,
#         'student': temp_student,
#         'academy': temp_academy,
#         'klass': temp_klass,
#         'exam': temp_exam,
#         'score': temp_score,
#         'question': temp_question,
#         'wallet': temp_wallet,
#         'transaction': temp_transaction,
#     }
#
#
# def teacher_dashboard(request):
#     temp_user = request.user
#     temp_profile = Profile.objects.get(user=temp_user)
#     temp_teacher = Profile.objects.get(Q(user=temp_user) & Q(user__is_teacher=True))
#     temp_academy = temp_profile.academy
#     temp_klass = Klass.objects.filter(teacher=temp_profile)
#     temp_student = Profile.objects.filter(
#         Q(user__profile__klass__teacher=temp_teacher) & Q(user__is_student=True))
#     temp_exam = Exam.objects.filter(exam_klass__teacher=temp_teacher)
#     temp_question = Question.objects.filter(creator=temp_teacher)
#     temp_score = StudentScore.objects.filter(student__user__profile__klass__teacher=temp_teacher)
#     temp_wallet = Wallet.objects.get(user=temp_user)
#     temp_transaction = Transaction.objects.filter(wallet__user=temp_user).order_by('-order_time')
#     return {
#         'is_teacher': True,
#         'user': temp_user,
#         'profile': temp_profile,
#         'teacher': temp_teacher,
#         'student': temp_student,
#         'academy': temp_academy,
#         'klass': temp_klass,
#         'exam': temp_exam,
#         'question': temp_question,
#         'score': temp_score,
#         'wallet': temp_wallet,
#         'transaction': temp_transaction,
#     }
#
#
# def student_dashboard(request):
#     temp_user = request.user
#     temp_profile = Profile.objects.get(user=temp_user)
#     temp_student = Profile.objects.get(Q(user=temp_user) & Q(user__is_student=True))
#     temp_academy = temp_profile.academy
#     temp_klass = temp_profile.klass.all()
#     try:
#         temp_klass = temp_klass[0]
#     except:
#         temp_klass = None
#     temp_exam = Exam.objects.filter(exam_klass=temp_klass)
#     temp_score = StudentScore.objects.filter(student=temp_student)
#     return {
#         'is_student': True,
#         'user': temp_user,

dashboard/templates/dashboard/supervisor_dashboard/exam_score.html
{% extends 'dashboard/dashboard_base.html' %}
{% load jalali_tags %}

{% block page_title %}
    لیست
    {{ page_name }}
    ها
{% endblock %}

{% block dashboard_heading %}

{% endblock %}

{% block dashboard_content %}
    <div class="col-lg-8 mb-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary d-inline">
                    لیست
                    {{ page_name }}
                    ها
                </h6>
            </div>
            <div class="card-body">
                {% if output_msg %}
                    <div class="alert alert-{{ output_msg.color }} text-center" role="alert">
                        {{ output_msg.text }}
                    </div>
                    <a href="{% url 'dashboard:exam_list' %}" type="submit" class="btn btn-light btn-block mt-2">
                        بازگشت به لیست
                        {{ page_name }}
                        ها
                    </a>
                    <a href="{% url 'dashboard:me_view' %}" type="submit" class="btn btn-light btn-block mt-2">
                        بازگشت به پنل کاربری
                    </a>
                {% elif all_out %}
                    {% for i in all_out %}
                        <div class="alert
                        {% if i.exam.is_active %}
                            alert-success
                        {% else %}
                            alert-secondary
                        {% endif %}
                        text-center pb-3" role="alert">
                            <a class="text-decoration-none text-dark mb-3">
                                آزمون:
                                {{ i.exam }}
                            </a>
                            <div class="row mt-3">
                                <div class="col-sm text-center">
                                    <table class="table table-borderless">
                                        <tbody>
                                        <tr>
                                            <th scope="col">تعداد کل سوالات:</th>
                                            <th scope="col">{{ i.exam.exam_question.count }}</th>
                                        </tr>
                                        <tr>
                                            <th scope="row">پاسخ های صحیح:</th>
                                            <td>{{ i.score.score|floatformat }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">درصد نمره:</th>
                                            <td>{{ i.score.percentage|floatformat }}%</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-sm text-center">
                                    <table class="table table-borderless">
                                        <tbody>
                                        <tr>
                                            <th scope="col">پاسخ داده شده:</th>
                                            <th scope="col">{{ i.score.all_questions }}</th>
                                        </tr>
                                        <tr>
                                            <th scope="row">نمره کل:</th>
                                            <td>{{ i.score.score|floatformat }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">وضعیت دانش آموز:</th>
                                            {% if i.eps %}
                                                <td>حاضر</td>
                                            {% elif i.exam.is_active %}
                                                <td>انتظار</td>
                                            {% else %}
                                                <td>غایب</td>
                                            {% endif %}
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-sm text-center">
                                    {% if i.exam.is_active %}
                                        {% if i.eps %}
                                            <span class="btn btn-outline-dark btn-sm btn-block">
                                                آزمون انجام شده است
                                            </span>
                                        {% else %}
                                            <a href="{% url 'dashboard:exam_info' exa_id=i.exam.pk %}"
                                               class="btn btn-outline-primary btn-sm btn-block">
                                                شرکت در آزمون
                                            </a>
                                        {% endif %}
                                    {% else %}
                                        <span class="btn btn-outline-danger btn-sm btn-block">
                                    زمان آزمون گذشته است
                                </span>
                                    {% endif %}
                                    <span class="btn btn-outline-dark btn-sm btn-block">
                                        زمان ورود:
                                        {{ i.eps.STU_start|to_jalali:'%Y/%m/%d, %H:%M' }}
                                </span>
                                    <span class="btn btn-outline-dark btn-sm btn-block">
                                        زمان خروج:
                                        {{ i.eps.STU_finish|to_jalali:'%Y/%m/%d, %H:%M' }}
                                </span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% include 'dashboard/_pagination_template.html' with function_return_name=all_out page_name='page' %}
                {% else %}
                    <div class="alert alert-danger text-center" role="alert">
                        {{ all_out.error }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/supervisor_dashboard/question_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% load jalali_tags %}

{% block page_title %}
    لیست
    {{ page_name }}
    ها
{% endblock %}

{% block dashboard_heading %}

{% endblock %}

{% block dashboard_content %}
    <div class="col-lg-8 mb-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-sm">
                        <h6 class="my-2 font-weight-bold text-primary d-inline-block">
                            لیست
                            {{ page_name }}
                            ها
                        </h6>
                        <a href="{% url 'dashboard:list_all' name='question' %}" class="badge badge-pill badge-info">
                            لیست کامل
                        </a>
                    </div>
                    <div class="col-sm">
                        <form method="post" action="" class="form-inline my-2 my-lg-0 float-lg-left">
                            {% csrf_token %}
                            <input class="form-control ml-sm-2" type="search" placeholder="نام سوال را وارد کنید"
                                   aria-label="Search" name="search_content">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                                جستجو
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-body">
                {% if output_msg %}
                    <div class="alert alert-{{ output_msg.color }} text-center" role="alert">
                        {{ output_msg.text }}
                    </div>
                    <a href="{% url 'dashboard:question_manage' %}" type="submit" class="btn btn-light btn-block mt-2">
                        بازگشت به لیست
                        {{ page_name }}
                        ها
                    </a>
                    <a href="{% url 'dashboard:me_view' %}" type="submit" class="btn btn-light btn-block mt-2">
                        بازگشت به پنل کاربری
                    </a>
                {% elif all_out %}
                    {% for i in all_out %}
                        <div class="alert
                        {% if i.question.is_active %}
                            alert-success
                        {% else %}
                            alert-secondary
                        {% endif %}
                        text-center pb-3" role="alert">
                            <a class="text-decoration-none text-dark mb-3">
                                سوال:
                                {{ i.question }}
                            </a>
                            <div class="row mt-3">
                                <div class="col-sm text-center">
                                    {% if i.question.is_active %}
                                        <span class="btn btn-outline-primary btn-sm btn-block">
                                                سوال فعال است
                                        </span>
                                    {% else %}
                                        <span class="btn btn-outline-danger btn-sm btn-block">
                                    سوال غیر فعال است
                                        </span>
                                    {% endif %}
                                    <span class="btn btn-outline-primary btn-sm btn-block">
                                                طراح:
                                        {{ i.question.creator.user.get_full_name }}
                                    </span>
                                    <span class="btn btn-outline-primary btn-sm btn-block">
                                                دسته بندی:
                                        {{ i.question.category.name }}
                                        -
                                        {{ i.question.category.parent.name }}
                                    </span>
                                    <span class="btn btn-outline-primary btn-sm btn-block">
                                                تاریخ انتشار:
                                        {{ i.question.publish_date|to_jalali:'%Y/%m/%d, %H:%M' }}
                                    </span>
                                    <a href="{% url 'dashboard:delete_uuid' name='question' obj_uuid=i.question.pk %}"
                                       class="btn btn-outline-danger btn-sm btn-block">
                                        حذف سوال
                                    </a>
                                </div>
                                <div class="col-sm text-center">
                                    {% for j in i.answers %}
                                        <span class="btn btn-outline-dark btn-sm btn-block">
                                        گزینه
                                            {{ j.choice_position }}
                                            :
                                        {{ j.choice_label }}
                                        </span>
                                    {% endfor %}
                                    <a href="{% url 'dashboard:question_change' qes_id=i.question.pk %}"
                                       class="btn btn-outline-info btn-sm btn-block">
                                        ویرایش سوال
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% include 'dashboard/_pagination_template.html' with function_return_name=all_out page_name='page' long='True' long_list=page_range %}
                {% else %}
                    <div class="alert alert-danger text-center" role="alert">
                        {{ all_out.error }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}